---
- name: Check if we have previously joined a Domain (RHEL7)
  shell: realm list -v {{adserver}}
  register: domainjoined

- debug: msg="... {{domainjoined}}"

- name: Joining to AD (RHEL7)
  shell: echo  {{psw}} | realm join -v -U {{aduser}} --computer-ou="{{domain_ou}}" {{adserver}}
  when: domainjoined.stderr == "No configured realms"
